### ISSUE TITLE
Can't use latest release

### ISSUE THREAD

**Issue by fonix232** [theapache64/abcd#8]
Downloaded the latest APK, and upon start it says there's an update. There's no update, and it makes this release unusable.

I find it an incredibly bad developer choice to enforce latest version of the app when there's no actual need for it. It also makes hosting older versions unnecessary.

**Comment by ColSep** [comment]
Same issue

**Comment by theapache64** [comment]
Did you check the playstore release?  https://play.google.com/store/apps/details?id=com.theapache64.abcd

**Comment by theapache64** [comment]
Closing this issue due to lack of response. Feel free to re-open if issue persists.
